package oneast.searchstrategies

import oneast.*
import query.Examples
import util.Logger

fun main() {
    val elems = listOf("a", "b", "c")
    val n = 2

    val seq = Partitions.generate(elems, n)
    // Lazily take first few outputs
    seq.take(100).forEach { println(it) }
}

class Partitioner(examples: Examples) : SearchStrategy(examples) {
    override fun candidates(
        c: SearchState,
        unification: OneUnification,
        introduceBlanks: Boolean,
        fastForwardBlanks: Boolean,
        sizeBound: Int,
        depthBound: Int,
        loggingSeed: SearchState,
        logger: Logger
    ): Sequence<SearchState> {
        if (c.noHoles()) return sequenceOf(c)

        fun fastForward(): Sequence<SearchState> {
            val ff = fastForward(c)
            return listOfNotNull(ff).asSequence()
        }

        if (c.noFillableHoles()) {
            return if (fastForwardBlanks) fastForward() else sequenceOf(c)
        }

        if (sizeBound == 0) return fastForward()

        val iToFill = c.shallowestFillableHole()?.first ?: error("Impossible")
        val ty = c.types[iToFill]
        val holes = ty.allHoles().filterIsInstance<TypeHole>()

        val assignments = Partitions.generate(holes, ty.variables().size)

        return assignments
            .map { c.mapTypeAtIndex(iToFill) { typ -> applyPartition(typ, it) } }
            .flatMap { newCandidate ->
                logger.count("Total candidates")
                val u = posUnification(newCandidate)
                if (u.ok()) {
                    // Committing a blank at the top-level is free
                    val cost = 1
                    TODO(
                        "Cost is number of holes. but maybe in partition enum no need for size bound"
                    )
                    TODO(
                        "As we introduce blanks DURING search, we actually want to" +
                                "conservatively fast forward at each step. When is fastForwardBlanks passed as true/false?"
                    )
                    candidates(
                        newCandidate,
                        u,
                        introduceBlanks,
                        fastForwardBlanks,
                        sizeBound - cost,
                        depthBound,
                        loggingSeed,
                        logger
                    )
                } else emptySequence()
            }
    }

    /**
     * TODO I think this is slightly less efficient than if we implemented Types.replaceAll that
     * traverses down the tree just once and checks if each hole should be replaced
     */
    private fun replaceAll(type: Type, holes: List<TypeHole>, replacement: () -> Type) =
        holes.fold(type) { acc, hole -> acc.replace(hole, replacement()) }

    private fun applyPartition(type: Type, partition: PartitionResult<TypeHole>): Type {
        var fresh = type.variables().size
        return partition.blocks.foldIndexed(type) { block, acc, holes ->
            val replacement: () -> Type =
                /*
                IGNORE the IntelliJ code fix suggestion to [make] block the subject of the when!
                This breaks correctness, since when statements can only compare elements of the same type.
                Since [labelledBlockIndex] is an Int?, it will never match against [block], even when its
                runtime value is actually a non-null integer equal to [block].
                  */
                when {
                    block == partition.labelledBlockIndex -> {
                        { Blank(labelOnly = true) }
                    }
                    block in partition.assignments -> {
                        { Variable(partition.assignments[block]!!) }
                    }
                    else -> {
                        { Variable(fresh++) }
                    }
                }
            replaceAll(acc, holes, replacement)
        }
    }
}

/**
 * The code below was generated by Codex 5.2 with the following prompt:
 *
 * Generate all partitions of a list of elements, from smallest partition (all elements in one set)
 * to largest (all elements in separate sets). It doesn't matter how we order within each partition
 * size, but it matters that all partitions of size 2 are generated before all those of size 3.
 *
 * Each partition contains some blocks. For each partition, generate a subsequence of outputs; these
 * will all be flatmapped into one sequence. Each subsequence is as follows. We have some partition
 * containing m blocks. We also have some number n. We can eiher set aside one of the blocks as a
 * "labelled" blocks, or not. For the remaining blocks (all of them if we chose not to have a
 * labelled set), generate all possible ways of INJECTIVELY assigning SOME SUBSET of the numbers 0
 * to n to SOME SUBSET of the blocks. That is, not all the blocks need be assigned to a number, and
 * not all numbers up to n need be assigned to a block. Equivalently, we pick some k leq n and
 * enumerate all witnesses of nPk.
 *
 * There should be no duplicates whatsoever. The entire sequence should be lazily generated.
 */
data class PartitionResult<T>(
    val blocks: List<List<T>>,
    val labelledBlockIndex: Int?, // null = no labelled block
    val assignments: Map<Int, Int> // blockIndex -> number in 0..n-1
)

object Partitions {
    /**
     * Generate all partitions of elements, ordered by size (1 block, 2 blocks, ...), and for each
     * partition generate labelled-block choices and partial injective assignments.
     */
    fun <T> generate(elements: List<T>, n: Int): Sequence<PartitionResult<T>> = sequence {
        val m = elements.size
        for (k in 1..m) {
            // partitions with exactly k blocks
            for (blocks in partitionsOfSize(elements, k)) {
                val blockCount = blocks.size

                // labelled block choices: none + each block
                val labelledChoices: Sequence<Int?> = sequence {
                    yield(null)
                    for (i in 0 until blockCount) yield(i)
                }

                for (labelled in labelledChoices) {
                    val remainingBlockIndices = (0 until blockCount).filter { it != labelled }

                    // all partial injections from remaining blocks to numbers 0..n-1
                    for (assignment in partialInjectiveAssignments(remainingBlockIndices, n)) {
                        yield(
                            PartitionResult(
                                blocks = blocks,
                                labelledBlockIndex = labelled,
                                assignments = assignment
                            )
                        )
                    }
                }
            }
        }
    }

    /**
     * Generate all partitions of the elements into exactly k blocks, lazily. Uses restricted growth
     * strings (RGS) with max = k-1.
     */
    private fun <T> partitionsOfSize(elements: List<T>, k: Int): Sequence<List<List<T>>> =
        sequence {
            val m = elements.size
            if (k < 1 || k > m) return@sequence

            val rgs = IntArray(m)
            rgs[0] = 0

            suspend fun SequenceScope<List<List<T>>>.recurse(pos: Int, maxUsed: Int) {
                if (pos == m) {
                    if (maxUsed == k - 1) {
                        yield(rgsToBlocks(elements, rgs, k))
                    }
                    return
                }

                val remaining = m - pos - 1
                val maxCandidate = minOf(maxUsed + 1, k - 1)

                for (v in 0..maxCandidate) {
                    val newMax = if (v > maxUsed) v else maxUsed
                    val canReach = newMax + remaining >= k - 1
                    if (!canReach) continue

                    rgs[pos] = v
                    recurse(pos + 1, newMax)
                }
            }

            recurse(1, 0)
        }

    private fun <T> rgsToBlocks(elements: List<T>, rgs: IntArray, k: Int): List<List<T>> {
        val blocks = List(k) { mutableListOf<T>() }
        for (i in elements.indices) {
            blocks[rgs[i]].add(elements[i])
        }
        return blocks
    }

    /**
     * Generate all partial injective assignments from given block indices to numbers 0..n-1.
     * Returns maps: blockIndex -> number.
     */
    private fun partialInjectiveAssignments(
        blockIndices: List<Int>,
        n: Int
    ): Sequence<Map<Int, Int>> = sequence {
        val used = BooleanArray(n)
        val current = mutableMapOf<Int, Int>()

        suspend fun SequenceScope<Map<Int, Int>>.backtrack(i: Int) {
            if (i == blockIndices.size) {
                yield(current.toMap())
                return
            }
            val block = blockIndices[i]

            // Option 1: leave unassigned
            backtrack(i + 1)

            // Option 2: assign any unused number
            for (num in 0 until n) {
                if (!used[num]) {
                    used[num] = true
                    current[block] = num
                    backtrack(i + 1)
                    current.remove(block)
                    used[num] = false
                }
            }
        }

        backtrack(0)
    }
}
