(int (i))	(bool (b))	(dii (d (i) (i)))	(dbi (d (b) (i)))	(dib (d (i) (b)))	(dbb (d (b) (b)))	(put (-> (d k v) (-> k (-> v (d k v)))))	(chain (-> (d a b) (-> (d b c) (d a c))))
(+ int)
(+ bool)
(+ dii)

(+ (put (chain dib dbi) int int))
(+ (put (chain dib dbb) int bool))
(- (put (chain dib dbb) int int))
(+ (chain dib dbb))
(+ (chain dbb dbb))
(+ (chain dib dbi))
(+ (chain dii dii))
(+ (chain dii dib))
(- (chain dib dib))
(- (chain dbi dbi))
(- (chain dib dii))
(- (chain dbi dbb))
(- (chain dbb dib))
(- (chain dii dbi))

(+ (put dii int int))
(+ (chain dii dii))
(+ (chain dii (put dii int int)))
(+ (chain dib dbi))
(+ (chain dib (put dbi bool int)))
(+ (chain dib (chain dbi dii)))
(+ (chain dib (chain dbi (put dii int int))))
(+ (chain dib (chain dbi (chain dii dii))))
(+ (chain dib (chain dbi (chain dii (put dii int int)))))
(+ (chain dii (chain dii dii)))
(+ (chain dii (chain dii (put dii int int))))
(+ (chain dii (chain dib dbi)))
(+ (chain dii (chain dib (put dbi bool int))))
(+ (chain dii (chain dib (chain dbi dii))))
(+ (chain dii (chain dib (chain dbi (put dii int int)))))
(+ (chain dii (chain dib (chain dbi (chain dii dii)))))
(+ (chain dii (chain dib (chain dbi (chain dii (put dii int int))))))
(+ (chain dib (chain dbb dbi)))
(+ (chain dib (chain dbb (put dbi bool int))))
(+ (chain dib (chain dbb (chain dbi dii))))
(+ (chain dib (chain dbb (chain dbi (put dii int int)))))
(+ (chain dib (chain dbb (chain dbi (chain dii dii)))))
(+ (chain dib (chain dbb (chain dbi (chain dii (put dii int int))))))
(+ (chain dib (chain dbi (chain dib dbi))))
(+ (chain dib (chain dbi (chain dib (put dbi bool int)))))
(+ (chain dib (chain dbi (chain dib (chain dbi dii)))))
(+ (chain dib (chain dbi (chain dib (chain dbi (put dii int int))))))
(+ (chain dib (chain dbi (chain dib (chain dbi (chain dii dii))))))
(+ (chain dib (chain dbi (chain dib (chain dbi (chain dii (put dii int int)))))))
(+ (chain dib (chain dbi (chain dii (chain dii dii)))))
(+ (chain dib (chain dbi (chain dii (chain dii (put dii int int))))))
(+ (chain dib (chain dbi (chain dii (chain dib dbi)))))
(+ (chain dib (chain dbi (chain dii (chain dib (put dbi bool int))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi dii))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (put dii int int)))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (chain dii dii)))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dii int int))))))))
(+ dbi)
(+ (put dbi bool int))
(+ (chain dbi dii))
(+ (chain dbi (put dii int int)))
(+ (chain dbi (chain dii dii)))
(+ (chain dbi (chain dii (put dii int int))))
(+ (chain dbb dbi))
(+ (chain dbb (put dbi bool int)))
(+ (chain dbb (chain dbi dii)))
(+ (chain dbb (chain dbi (put dii int int))))
(+ (chain dbb (chain dbi (chain dii dii))))
(+ (chain dbb (chain dbi (chain dii (put dii int int)))))
(+ (chain dbi (chain dib dbi)))
(+ (chain dbi (chain dib (put dbi bool int))))
(+ (chain dbi (chain dib (chain dbi dii))))
(+ (chain dbi (chain dib (chain dbi (put dii int int)))))
(+ (chain dbi (chain dib (chain dbi (chain dii dii)))))
(+ (chain dbi (chain dib (chain dbi (chain dii (put dii int int))))))
(+ (chain dbi (chain dii (chain dii dii))))
(+ (chain dbi (chain dii (chain dii (put dii int int)))))
(+ (chain dbi (chain dii (chain dib dbi))))
(+ (chain dbi (chain dii (chain dib (put dbi bool int)))))
(+ (chain dbi (chain dii (chain dib (chain dbi dii)))))
(+ (chain dbi (chain dii (chain dib (chain dbi (put dii int int))))))
(+ (chain dbi (chain dii (chain dib (chain dbi (chain dii dii))))))
(+ (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dii int int)))))))
(+ (chain dbb (chain dbb dbi)))
(+ (chain dbb (chain dbb (put dbi bool int))))
(+ (chain dbb (chain dbb (chain dbi dii))))
(+ (chain dbb (chain dbb (chain dbi (put dii int int)))))
(+ (chain dbb (chain dbb (chain dbi (chain dii dii)))))
(+ (chain dbb (chain dbb (chain dbi (chain dii (put dii int int))))))
(+ (chain dbb (chain dbi (chain dib dbi))))
(+ (chain dbb (chain dbi (chain dib (put dbi bool int)))))
(+ (chain dbb (chain dbi (chain dib (chain dbi dii)))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (put dii int int))))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (chain dii dii))))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (chain dii (put dii int int)))))))
(+ (chain dbb (chain dbi (chain dii (chain dii dii)))))
(+ (chain dbb (chain dbi (chain dii (chain dii (put dii int int))))))
(+ (chain dbb (chain dbi (chain dii (chain dib dbi)))))
(+ (chain dbb (chain dbi (chain dii (chain dib (put dbi bool int))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi dii))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (put dii int int)))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (chain dii dii)))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dii int int))))))))
(+ dib)
(+ (put dib int bool))
(+ (chain dii dib))
(+ (chain dii (put dib int bool)))
(+ (chain dib dbb))
(+ (chain dib (put dbb bool bool)))
(+ (chain dib (chain dbi dib)))
(+ (chain dib (chain dbi (put dib int bool))))
(+ (chain dib (chain dbi (chain dii dib))))
(+ (chain dib (chain dbi (chain dii (put dib int bool)))))
(+ (chain dii (chain dii dib)))
(+ (chain dii (chain dii (put dib int bool))))
(+ (chain dii (chain dib dbb)))
(+ (chain dii (chain dib (put dbb bool bool))))
(+ (chain dii (chain dib (chain dbi dib))))
(+ (chain dii (chain dib (chain dbi (put dib int bool)))))
(+ (chain dii (chain dib (chain dbi (chain dii dib)))))
(+ (chain dii (chain dib (chain dbi (chain dii (put dib int bool))))))
(+ (chain dib (chain dbb dbb)))
(+ (chain dib (chain dbb (put dbb bool bool))))
(+ (chain dib (chain dbb (chain dbi dib))))
(+ (chain dib (chain dbb (chain dbi (put dib int bool)))))
(+ (chain dib (chain dbb (chain dbi (chain dii dib)))))
(+ (chain dib (chain dbb (chain dbi (chain dii (put dib int bool))))))
(+ (chain dib (chain dbi (chain dib dbb))))
(+ (chain dib (chain dbi (chain dib (put dbb bool bool)))))
(+ (chain dib (chain dbi (chain dib (chain dbi dib)))))
(+ (chain dib (chain dbi (chain dib (chain dbi (put dib int bool))))))
(+ (chain dib (chain dbi (chain dib (chain dbi (chain dii dib))))))
(+ (chain dib (chain dbi (chain dib (chain dbi (chain dii (put dib int bool)))))))
(+ (chain dib (chain dbi (chain dii (chain dii dib)))))
(+ (chain dib (chain dbi (chain dii (chain dii (put dib int bool))))))
(+ (chain dib (chain dbi (chain dii (chain dib dbb)))))
(+ (chain dib (chain dbi (chain dii (chain dib (put dbb bool bool))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi dib))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (put dib int bool)))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (chain dii dib)))))))
(+ (chain dib (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dib int bool))))))))
(+ dbb)
(+ (put dbb bool bool))
(+ (chain dbi dib))
(+ (chain dbi (put dib int bool)))
(+ (chain dbi (chain dii dib)))
(+ (chain dbi (chain dii (put dib int bool))))
(+ (chain dbb dbb))
(+ (chain dbb (put dbb bool bool)))
(+ (chain dbb (chain dbi dib)))
(+ (chain dbb (chain dbi (put dib int bool))))
(+ (chain dbb (chain dbi (chain dii dib))))
(+ (chain dbb (chain dbi (chain dii (put dib int bool)))))
(+ (chain dbi (chain dib dbb)))
(+ (chain dbi (chain dib (put dbb bool bool))))
(+ (chain dbi (chain dib (chain dbi dib))))
(+ (chain dbi (chain dib (chain dbi (put dib int bool)))))
(+ (chain dbi (chain dib (chain dbi (chain dii dib)))))
(+ (chain dbi (chain dib (chain dbi (chain dii (put dib int bool))))))
(+ (chain dbi (chain dii (chain dii dib))))
(+ (chain dbi (chain dii (chain dii (put dib int bool)))))
(+ (chain dbi (chain dii (chain dib dbb))))
(+ (chain dbi (chain dii (chain dib (put dbb bool bool)))))
(+ (chain dbi (chain dii (chain dib (chain dbi dib)))))
(+ (chain dbi (chain dii (chain dib (chain dbi (put dib int bool))))))
(+ (chain dbi (chain dii (chain dib (chain dbi (chain dii dib))))))
(+ (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dib int bool)))))))
(+ (chain dbb (chain dbb dbb)))
(+ (chain dbb (chain dbb (put dbb bool bool))))
(+ (chain dbb (chain dbb (chain dbi dib))))
(+ (chain dbb (chain dbb (chain dbi (put dib int bool)))))
(+ (chain dbb (chain dbb (chain dbi (chain dii dib)))))
(+ (chain dbb (chain dbb (chain dbi (chain dii (put dib int bool))))))
(+ (chain dbb (chain dbi (chain dib dbb))))
(+ (chain dbb (chain dbi (chain dib (put dbb bool bool)))))
(+ (chain dbb (chain dbi (chain dib (chain dbi dib)))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (put dib int bool))))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (chain dii dib))))))
(+ (chain dbb (chain dbi (chain dib (chain dbi (chain dii (put dib int bool)))))))
(+ (chain dbb (chain dbi (chain dii (chain dii dib)))))
(+ (chain dbb (chain dbi (chain dii (chain dii (put dib int bool))))))
(+ (chain dbb (chain dbi (chain dii (chain dib dbb)))))
(+ (chain dbb (chain dbi (chain dii (chain dib (put dbb bool bool))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi dib))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (put dib int bool)))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (chain dii dib)))))))
(+ (chain dbb (chain dbi (chain dii (chain dib (chain dbi (chain dii (put dib int bool))))))))
(+ (put dii))
(+ (put (put dii int int)))
(+ (put (chain dii dii)))
(+ (put (chain dii (put dii int int))))
(+ (put (chain dib dbi)))
(+ (put (chain dib (put dbi bool int))))
(+ (put (chain dib (chain dbi dii))))
(+ (put (chain dib (chain dbi (put dii int int)))))
(+ (put (chain dib (chain dbi (chain dii dii)))))
(+ (put (chain dib (chain dbi (chain dii (put dii int int))))))
(+ (put dbi))
(+ (put (put dbi bool int)))
(+ (put (chain dbi dii)))
(+ (put (chain dbi (put dii int int))))
(+ (put (chain dbi (chain dii dii))))
(+ (put (chain dbi (chain dii (put dii int int)))))
(+ (put (chain dbb dbi)))
(+ (put (chain dbb (put dbi bool int))))
(+ (put (chain dbb (chain dbi dii))))
(+ (put (chain dbb (chain dbi (put dii int int)))))
(+ (put (chain dbb (chain dbi (chain dii dii)))))
(+ (put (chain dbb (chain dbi (chain dii (put dii int int))))))
(+ (put dib))
(+ (put (put dib int bool)))
(+ (put (chain dii dib)))
(+ (put (chain dii (put dib int bool))))
(+ (put (chain dib dbb)))
(+ (put (chain dib (put dbb bool bool))))
(+ (put (chain dib (chain dbi dib))))
(+ (put (chain dib (chain dbi (put dib int bool)))))
(+ (put (chain dib (chain dbi (chain dii dib)))))
(+ (put (chain dib (chain dbi (chain dii (put dib int bool))))))
(+ (put dbb))
(+ (put (put dbb bool bool)))
(+ (put (chain dbi dib)))
(+ (put (chain dbi (put dib int bool))))
(+ (put (chain dbi (chain dii dib))))
(+ (put (chain dbi (chain dii (put dib int bool)))))
(+ (put (chain dbb dbb)))
(+ (put (chain dbb (put dbb bool bool))))
(+ (put (chain dbb (chain dbi dib))))
(+ (put (chain dbb (chain dbi (put dib int bool)))))
(+ (put (chain dbb (chain dbi (chain dii dib)))))
(+ (put (chain dbb (chain dbi (chain dii (put dib int bool))))))
(+ (put dii int))
(+ (put dbi bool))
(+ (put dib int))
(+ (put dbb bool))
(+ (chain dii))
(+ (chain (put dii int int)))
(+ (chain (chain dii dii)))
(+ (chain (chain dii (put dii int int))))
(+ (chain (chain dib dbi)))
(+ (chain (chain dib (put dbi bool int))))
(+ (chain (chain dib (chain dbi dii))))
(+ (chain (chain dib (chain dbi (put dii int int)))))
(+ (chain (chain dib (chain dbi (chain dii dii)))))
(+ (chain (chain dib (chain dbi (chain dii (put dii int int))))))
(+ (chain dbi))
(+ (chain (put dbi bool int)))
(+ (chain (chain dbi dii)))
(+ (chain (chain dbi (put dii int int))))
(+ (chain (chain dbi (chain dii dii))))
(+ (chain (chain dbi (chain dii (put dii int int)))))
(+ (chain (chain dbb dbi)))
(+ (chain (chain dbb (put dbi bool int))))
(+ (chain (chain dbb (chain dbi dii))))
(+ (chain (chain dbb (chain dbi (put dii int int)))))
(+ (chain (chain dbb (chain dbi (chain dii dii)))))
(+ (chain (chain dbb (chain dbi (chain dii (put dii int int))))))
(+ (chain dib))
(+ (chain (put dib int bool)))
(+ (chain (chain dii dib)))
(+ (chain (chain dii (put dib int bool))))
(+ (chain (chain dib dbb)))
(+ (chain (chain dib (put dbb bool bool))))
(+ (chain (chain dib (chain dbi dib))))
(+ (chain (chain dib (chain dbi (put dib int bool)))))
(+ (chain (chain dib (chain dbi (chain dii dib)))))
(+ (chain (chain dib (chain dbi (chain dii (put dib int bool))))))
(+ (chain dbb))
(+ (chain (put dbb bool bool)))
(+ (chain (chain dbi dib)))
(+ (chain (chain dbi (put dib int bool))))
(+ (chain (chain dbi (chain dii dib))))
(+ (chain (chain dbi (chain dii (put dib int bool)))))
(+ (chain (chain dbb dbb)))
(+ (chain (chain dbb (put dbb bool bool))))
(+ (chain (chain dbb (chain dbi dib))))
(+ (chain (chain dbb (chain dbi (put dib int bool)))))
(+ (chain (chain dbb (chain dbi (chain dii dib)))))
(+ (chain (chain dbb (chain dbi (chain dii (put dib int bool))))))
(+ put)
(+ chain)
(- (put dii (put dii)))
(- (put dii (put dbi)))
(- (put dii (put dib)))
(- (put dii (put dbb)))
(- (put dbi (put dii)))
(- (put dbi (put dbi)))
(- (put dbi (put dib)))
(- (put dbi (put dbb)))
(- (put dbi (put dii int)))
(- (put dib (put dii)))
(- (put dib (put dbi)))
(- (put dib (put dib)))
(- (put dib (put dbb)))
(- (put dib (put dii int)))
(- (put dib (put dbi bool)))
(- (put dbb (put dii)))
(- (put dbb (put dbi)))
(- (put dbb (put dib)))
(- (put dbb (put dbb)))
(- (put dbb (put dii int)))
(- (put dbb (put dbi bool)))
(- (put dbb (put dib int)))
(- (put dii int (put dii)))
(- (put dii int (put dbi)))
(- (put dii int (put dib)))
(- (put dii int (put dbb)))
(- (put dii int (put dii int)))
(- (put dii int (put dbi bool)))
(- (put dii int (put dib int)))
(- (put dii int (put dbb bool)))
(- (put dbi bool (put dii)))
(- (put dbi bool (put dbi)))
(- (put dbi bool (put dib)))
(- (put dbi bool (put dbb)))
(- (put dbi bool (put dii int)))
(- (put dbi bool (put dbi bool)))
(- (put dbi bool (put dib int)))
(- (put dbi bool (put dbb bool)))
(- (put dib int (put dii)))
(- (put dib int (put dbi)))
(- (put dib int (put dib)))
(- (put dib int (put dbb)))
(- (put dib int (put dii int)))
(- (put dib int (put dbi bool)))
(- (put dib int (put dib int)))
(- (put dib int (put dbb bool)))
(- (put dbb bool (put dii)))
(- (put dbb bool (put dbi)))
(- (put dbb bool (put dib)))
(- (put dbb bool (put dbb)))
(- (put dbb bool (put dii int)))
(- (put dbb bool (put dbi bool)))
(- (put dbb bool (put dib int)))
(- (put dbb bool (put dbb bool)))
(- (chain (put dii)))
(- (chain (put dbi)))
(- (chain (put dib)))
(- (chain (put dbb)))
(- (chain (put dii int)))
(- (chain (put dbi bool)))
(- (chain (put dib int)))
(- (chain (put dbb bool)))
(- (chain dii (put dii)))
(- (chain dii (put dbi)))
(- (chain dii (put dib)))
(- (chain dii (put dbb)))
(- (chain dii (put dii int)))
(- (chain dii (put dbi bool)))
(- (chain dii (put dib int)))
(- (chain dii (put dbb bool)))
(- (chain dii (chain dii)))
(- (chain dii (chain (put dii int int))))
(- (chain dii (chain dbi)))
(- (chain dii (chain (put dbi bool int))))
(- (chain dii (chain dib)))
(- (chain dii (chain (put dib int bool))))
(- (chain dii (chain dbb)))
(- (chain dii (chain (put dbb bool bool))))
(- (chain dbi (put dii)))
(- (chain dbi (put dbi)))
(- (chain dbi (put dib)))
(- (chain dbi (put dbb)))
(- (chain dbi (put dii int)))
(- (chain dbi (put dbi bool)))
(- (chain dbi (put dib int)))
(- (chain dbi (put dbb bool)))
(- (chain dbi (chain dii)))
(- (chain dbi (chain (put dii int int))))
(- (chain dbi (chain dbi)))
(- (chain dbi (chain (put dbi bool int))))
(- (chain dbi (chain dib)))
(- (chain dbi (chain (put dib int bool))))
(- (chain dbi (chain dbb)))
(- (chain dbi (chain (put dbb bool bool))))
(- (chain dib (put dii)))
(- (chain dib (put dbi)))
(- (chain dib (put dib)))
(- (chain dib (put dbb)))
(- (chain dib (put dii int)))
(- (chain dib (put dbi bool)))
(- (chain dib (put dib int)))
(- (chain dib (put dbb bool)))
(- (chain dib (chain dii)))
(- (chain dib (chain (put dii int int))))
(- (chain dib (chain dbi)))
(- (chain dib (chain (put dbi bool int))))
(- (chain dib (chain dib)))
(- (chain dib (chain (put dib int bool))))
(- (chain dib (chain dbb)))
(- (chain dib (chain (put dbb bool bool))))
(- (chain dbb (put dii)))
(- (chain dbb (put dbi)))
(- (chain dbb (put dib)))
(- (chain dbb (put dbb)))
(- (chain dbb (put dii int)))
(- (chain dbb (put dbi bool)))
(- (chain dbb (put dib int)))
(- (chain dbb (put dbb bool)))
(- (chain dbb (chain dii)))
(- (chain dbb (chain (put dii int int))))
(- (chain dbb (chain dbi)))
(- (chain dbb (chain (put dbi bool int))))
(- (chain dbb (chain dib)))
(- (chain dbb (chain (put dib int bool))))
(- (chain dbb (chain dbb)))
(- (chain dbb (chain (put dbb bool bool))))
(- (put (put dii)))
(- (put (put (put dii int int))))
(- (put (put (chain dii dii))))
(- (put (put (chain dii (put dii int int)))))
(- (put (put (chain dib dbi))))
(- (put (put (chain dib (put dbi bool int)))))
(- (put (put (chain dib (chain dbi dii)))))
(- (put (put (chain dib (chain dbi (put dii int int))))))
(- (put (put (chain dib (chain dbi (chain dii dii))))))
(- (put (put (chain dib (chain dbi (chain dii (put dii int int)))))))
(- (put (put dbi)))
(- (put (put (put dbi bool int))))
(- (put (put (chain dbi dii))))
(- (put (put (chain dbi (put dii int int)))))
(- (put (put (chain dbi (chain dii dii)))))
(- (put (put (chain dbi (chain dii (put dii int int))))))
(- (put (put (chain dbb dbi))))
(- (put (put (chain dbb (put dbi bool int)))))
(- (put (put (chain dbb (chain dbi dii)))))
(- (put (put (chain dbb (chain dbi (put dii int int))))))
(- (put (put (chain dbb (chain dbi (chain dii dii))))))
(- (put (put (chain dbb (chain dbi (chain dii (put dii int int)))))))
(- (put (put dib)))
(- (put (put (put dib int bool))))
(- (put (put (chain dii dib))))
(- (put (put (chain dii (put dib int bool)))))
(- (put (put (chain dib dbb))))
(- (put (put (chain dib (put dbb bool bool)))))
(- (put (put (chain dib (chain dbi dib)))))
(- (put (put (chain dib (chain dbi (put dib int bool))))))
(- (put (put (chain dib (chain dbi (chain dii dib))))))
(- (put (put (chain dib (chain dbi (chain dii (put dib int bool)))))))
(- (put (put dbb)))
(- (put (put (put dbb bool bool))))
(- (put (put (chain dbi dib))))
(- (put (put (chain dbi (put dib int bool)))))
(- (put (put (chain dbi (chain dii dib)))))
(- (put (put (chain dbi (chain dii (put dib int bool))))))
(- (put (put (chain dbb dbb))))
(- (put (put (chain dbb (put dbb bool bool)))))
(- (put (put (chain dbb (chain dbi dib)))))
(- (put (put (chain dbb (chain dbi (put dib int bool))))))
(- (put (put (chain dbb (chain dbi (chain dii dib))))))
(- (put (put (chain dbb (chain dbi (chain dii (put dib int bool)))))))
(- (put (put dii int)))
(- (put (put dbi bool)))
(- (put (put dib int)))
(- (put (put dbb bool)))
(- (put (chain dii)))
(- (put (chain (put dii int int))))
(- (put (chain dbi)))
(- (put (chain (put dbi bool int))))
(- (put (chain dib)))
(- (put (chain (put dib int bool))))
(- (put (chain dbb)))
(- (put (chain (put dbb bool bool))))
(- (put dii (put (put dii int int))))
(- (put dii (put (chain dii dii))))
(- (put dii (put (chain dii (put dii int int)))))
(- (put dii (put (chain dib dbi))))
(- (put dii (put (chain dib (put dbi bool int)))))
(- (put dii (put (chain dib (chain dbi dii)))))
(- (put dii (put (chain dib (chain dbi (put dii int int))))))
(- (put dii (put (chain dib (chain dbi (chain dii dii))))))
(- (put dii (put (chain dib (chain dbi (chain dii (put dii int int)))))))
(- (put dii (put (put dbi bool int))))
(- (put dii (put (chain dbi dii))))
(- (put dii (put (chain dbi (put dii int int)))))
(- (put dii (put (chain dbi (chain dii dii)))))
(- (put dii (put (chain dbi (chain dii (put dii int int))))))
(- (put dii (put (chain dbb dbi))))
(- (put dii (put (chain dbb (put dbi bool int)))))
(- (put dii (put (chain dbb (chain dbi dii)))))
(- (put dii (put (chain dbb (chain dbi (put dii int int))))))
(- (put int))
(- (put bool))
(- (put dii bool))
(- (put dii dii))
(- (put dii dbi))
(- (put dii dib))
(- (put dii dbb))
(- (put dbi int))
(- (put dbi dii))
(- (put dbi dbi))
(- (put dbi dib))
(- (put dbi dbb))
(- (put dib bool))
(- (put dib dii))
(- (put dib dbi))
(- (put dib dib))
(- (put dib dbb))
(- (put dbb int))
(- (put dbb dii))
(- (put dbb dbi))
(- (put dbb dib))
(- (put dbb dbb))
(- (put dii int bool))
(- (put dii int dii))
(- (put dii int (put dii int int)))
(- (put dii int dbi))
(- (put dii int dib))
(- (put dii int dbb))
(- (put dbi bool bool))
(- (put dbi bool dii))
(- (put dbi bool (put dii int int)))
(- (put dbi bool dbi))
(- (put dbi bool (put dbi bool int)))
(- (put dbi bool dib))
(- (put dbi bool dbb))
(- (put dib int int))
(- (put dib int dii))
(- (put dib int (put dii int int)))
(- (put dib int dbi))
(- (put dib int (put dbi bool int)))
(- (put dib int dib))
(- (put dib int (put dib int bool)))
(- (put dib int dbb))
(- (put dbb bool int))
(- (put dbb bool dii))
(- (put dbb bool (put dii int int)))
(- (put dbb bool dbi))
(- (put dbb bool (put dbi bool int)))
(- (put dbb bool dib))
(- (put dbb bool (put dib int bool)))
(- (put dbb bool dbb))
(- (put dbb bool (put dbb bool bool)))
(- (chain int))
(- (chain bool))
(- (chain dii int))
(- (chain dii bool))
(- (chain dii dbi))
(- (chain dii (put dbi bool int)))
(- (chain dii dbb))
(- (chain dii (put dbb bool bool)))
(- (chain dbi int))
(- (chain dbi bool))
(- (chain dbi dbi))
(- (chain dbi (put dbi bool int)))
(- (chain dbi (chain dbi dii)))
(- (chain dbi (chain dbi (put dii int int))))
(- (chain dbi (chain dbi (chain dii dii))))
(- (chain dbi (chain dbi (chain dii (put dii int int)))))
(- (chain dbi dbb))
(- (chain dbi (put dbb bool bool)))
(- (chain dbi (chain dbi dib)))
(- (chain dbi (chain dbi (put dib int bool))))
(- (chain dbi (chain dbi (chain dii dib))))
(- (chain dbi (chain dbi (chain dii (put dib int bool)))))
(- (chain dib int))
(- (chain dib bool))
(- (chain dib dii))
(- (chain dib (put dii int int)))
(- (chain dib (chain dii dii)))
(- (chain dib (chain dii (put dii int int))))
(- (chain dib (chain dib dbi)))
(- (chain dib (chain dib (put dbi bool int))))
(- (chain dib (chain dib (chain dbi dii))))
(- (chain dib (chain dib (chain dbi (put dii int int)))))
(- (chain dib (chain dib (chain dbi (chain dii dii)))))
(- (chain dib (chain dib (chain dbi (chain dii (put dii int int))))))
(- (chain dib dib))
(- (chain dib (put dib int bool)))
(- (chain dib (chain dii dib)))
(- (chain dib (chain dii (put dib int bool))))
(- (chain dib (chain dib dbb)))
(- (chain dib (chain dib (put dbb bool bool))))
(- (chain dib (chain dib (chain dbi dib))))
(- (chain dib (chain dib (chain dbi (put dib int bool)))))
(- (chain dib (chain dib (chain dbi (chain dii dib)))))
(- (chain dib (chain dib (chain dbi (chain dii (put dib int bool))))))
(- (chain dbb int))
(- (chain dbb bool))
(- (chain dbb dii))
(- (chain dbb (put dii int int)))
(- (chain dbb (chain dii dii)))
(- (chain dbb (chain dii (put dii int int))))
(- (chain dbb (chain dib dbi)))
(- (chain dbb (chain dib (put dbi bool int))))
(- (chain dbb (chain dib (chain dbi dii))))
(- (chain dbb (chain dib (chain dbi (put dii int int)))))
(- (chain dbb (chain dib (chain dbi (chain dii dii)))))
(- (chain dbb (chain dib (chain dbi (chain dii (put dii int int))))))
(- (chain dbb dib))
(- (chain dbb (put dib int bool)))
(- (chain dbb (chain dii dib)))
(- (chain dbb (chain dii (put dib int bool))))
(- (chain dbb (chain dib dbb)))
(- (chain dbb (chain dib (put dbb bool bool))))
(- (chain dbb (chain dib (chain dbi dib))))
(- (chain dbb (chain dib (chain dbi (put dib int bool)))))
(- (chain dbb (chain dib (chain dbi (chain dii dib)))))
(- (chain dbb (chain dib (chain dbi (chain dii (put dib int bool))))))
(- (put dii (put dii int int)))
(- (put dii (chain dii dii)))
(- (put dii (chain dii (put dii int int))))
(- (put dii (chain dib dbi)))
(- (put dii (chain dib (put dbi bool int))))
(- (put dii (chain dib (chain dbi dii))))
(- (put dii (chain dib (chain dbi (put dii int int)))))
(- (put dii (chain dib (chain dbi (chain dii dii)))))
(- (put dii (chain dib (chain dbi (chain dii (put dii int int))))))
(- (put dii (put dbi bool int)))
(- (put dii (chain dbi dii)))
(- (put dii (chain dbi (put dii int int))))
(- (put dii (chain dbi (chain dii dii))))
(- (put dii (chain dbi (chain dii (put dii int int)))))
(- (put dii (chain dbb dbi)))
(- (put dii (chain dbb (put dbi bool int))))
(- (put dii (chain dbb (chain dbi dii))))
(- (put dii (chain dbb (chain dbi (put dii int int)))))
(- (put dii (chain dbb (chain dbi (chain dii dii)))))
(- (put dii (chain dbb (chain dbi (chain dii (put dii int int))))))
(- (put dii (put dib int bool)))
(- (put dii (chain dii dib)))
(- (put dii (chain dii (put dib int bool))))
(- (put dii (chain dib dbb)))
(- (put dii (chain dib (put dbb bool bool))))
(- (put dii (chain dib (chain dbi dib))))
(- (put dii (chain dib (chain dbi (put dib int bool)))))
(- (put dii (chain dib (chain dbi (chain dii dib)))))
(- (put dii (chain dib (chain dbi (chain dii (put dib int bool))))))
(- (put dii (put dbb bool bool)))
(- (put dii (chain dbi dib)))
(- (put dii (chain dbi (put dib int bool))))
(- (put dii (chain dbi (chain dii dib))))
(- (put dii (chain dbi (chain dii (put dib int bool)))))
(- (put dii (chain dbb dbb)))
(- (put dii (chain dbb (put dbb bool bool))))
(- (put dii (chain dbb (chain dbi dib))))
(- (put dii (chain dbb (chain dbi (put dib int bool)))))
(- (put dii (chain dbb (chain dbi (chain dii dib)))))
(- (put dii (chain dbb (chain dbi (chain dii (put dib int bool))))))
(- (put dbi (put dii int int)))
(- (put dbi (chain dii dii)))
(- (put dbi (chain dii (put dii int int))))
(- (put dbi (chain dib dbi)))
(- (put dbi (chain dib (put dbi bool int))))
(- (put dbi (chain dib (chain dbi dii))))
(- (put dbi (chain dib (chain dbi (put dii int int)))))
(- (put dbi (chain dib (chain dbi (chain dii dii)))))
(- (put dbi (chain dib (chain dbi (chain dii (put dii int int))))))
(- (put dbi (put dbi bool int)))
(- (put dbi (chain dbi dii)))
(- (put dbi (chain dbi (put dii int int))))
(- (put dbi (chain dbi (chain dii dii))))
(- (put dbi (chain dbi (chain dii (put dii int int)))))
(- (put dbi (chain dbb dbi)))
(- (put dbi (chain dbb (put dbi bool int))))
(- (put dbi (chain dbb (chain dbi dii))))
(- (put dbi (chain dbb (chain dbi (put dii int int)))))
(- (put dbi (chain dbb (chain dbi (chain dii dii)))))
(- (put dbi (chain dbb (chain dbi (chain dii (put dii int int))))))
(- (put dbi (put dib int bool)))
(- (put dbi (chain dii dib)))
(- (put dbi (chain dii (put dib int bool))))
(- (put dbi (chain dib dbb)))
(- (put dbi (chain dib (put dbb bool bool))))
(- (put dbi (chain dib (chain dbi dib))))
(- (put dbi (chain dib (chain dbi (put dib int bool)))))
(- (put dbi (chain dib (chain dbi (chain dii dib)))))
(- (put dbi (chain dib (chain dbi (chain dii (put dib int bool))))))
(- (put dbi (put dbb bool bool)))
(- (put dbi (chain dbi dib)))
(- (put dbi (chain dbi (put dib int bool))))
(- (put dbi (chain dbi (chain dii dib))))
(- (put dbi (chain dbi (chain dii (put dib int bool)))))
(- (put dbi (chain dbb dbb)))
(- (put dbi (chain dbb (put dbb bool bool))))
(- (put dbi (chain dbb (chain dbi dib))))
(- (put dbi (chain dbb (chain dbi (put dib int bool)))))
(- (put dbi (chain dbb (chain dbi (chain dii dib)))))
(- (put dbi (chain dbb (chain dbi (chain dii (put dib int bool))))))
(- (put dib (put dii int int)))
(- (put dib (chain dii dii)))
