(+ Num)
(+ Li)
(+ LLi)
(+ cons)
(+ (cons Num))   
(+ (cons Num Li))
(+ (cons Num (cons Num Li)))   
(+ (cons Li))  
(+ (cons Li LLi))  
(+ (cons Li (cons Li LLi)))
(- (cons Li Num))
(- (cons LLi Li))  
(+ (cons LLi)) 
(+ (cons (cons Num Li))) 
(+ true) 
(+ Lb)
(+ (cons true))  
(+ (cons true Lb))  
(+ (cons true (cons true Lb)))
(- (cons Num Lb))   
(- (cons true Li))   
(- (cons Num LLi))   
(- (cons true LLi))  
(- (cons true (cons Num Li)))

// Remove subexprs


(+ (cons Num (cons Num Li)))
(+ (cons Li (cons Li LLi)))
(- (cons Li Num))
(- (cons LLi Li))
(+ (cons LLi))
(+ (cons (cons Num Li)))
(+ (cons true (cons true Lb)))
(- (cons Num Lb))
(- (cons true Li))
(- (cons Num LLi))
(- (cons true LLi))
(- (cons true (cons Num Li)))