(Num (i));(true (b));(Li (l (i)));(LLi (l (l (i))));(Lb (l (b)));(cons (-> a (-> (l a) (l a))))

(+ (cons Num (cons Num Li)))
(+ (cons Li (cons Li LLi)))
(- (cons Li Num))
(- (cons LLi Li))
(+ (cons LLi))
(+ (cons (cons Num Li)))
(+ (cons true (cons true Lb)))
(- (cons Num Lb))
(- (cons true Li))
(- (cons Num LLi))
(- (cons true LLi))
(- (cons true (cons Num Li)))
