(Num (i));(true (b));({} (d a b));(Eib (d (i) (b)));(Ebi (d (b) (i)));(Eii (d (i) (i)));(Ebb (d (b) (b)));(put (-> (d k v) (-> k (-> v (d k v)))))

(+ (put Eib))
(+ (put Eib Num))
(+ (put Eib Num))
(+ (put Eib Num true))
(+ (put (put Eib Num true)))
(+ (put (put Eib Num true)))
(+ (put (put Eib Num true) Num))
(+ (put (put Eib Num true) Num))
(+ (put (put Eib Num true) Num))
(+ (put (put Eib Num true) Num true))
(+ (put (put Eib Num true) Num true))
(+ (put (put Eib Num true) Num true))
(+ (put Ebi))
(+ (put Ebi true))
(+ (put Ebi true Num))
(+ (put (put Ebi true Num)))
(+ (put (put Ebi true Num) true))
(+ (put (put Ebi true Num) true Num))
(+ (put (put Ebi true Num) true Num))
(+ (put (put Ebi true Num) true))
(+ (put (put Ebi true Num) true Num))
(+ (put (put Eii Num Num) Num Num))
(- (put Num))
(- (put true))
(- (put Num))
(- (put (put Ebi)))
(- (put (put Ebi true)))
(- (put (put Eib)))
(- (put (put Eib Num)))
(- (put Ebi Num))
(- (put Eib true))
(- (put Eib Num Num))
(- (put Eib Num Num))
(- (put Ebi true true))
(- (put Eii (put Eii Num Num)))