({} (d a b));(put (-> (d k v) (-> k (-> v (d k v)))));(chain (-> (d a b) (-> (d b c) (d a c))));(Num (i));(true (b));(nil (l a));(cons (-> a (-> (l a) (l a))))

(+ (chain {} {}))
(+ (chain (put {} true true) (put {} true true)))
(+ (put (chain (put {} Num true) (put {} true Num)) Num Num))
(+ (put (put {} Num true) Num true))
(+ (put (chain (put {} Num true) (put {} true true)) Num true))
(+ (chain (put {} Num true) (chain (put {} true Num) (put {} Num Num))))
(+ (chain (put {} Num Num) (chain (put {} Num true) (put (put {} true Num) true Num))))
(+ (chain {} (put {} Num true)))
(+ (chain (put {} true Num) (put (put {} Num Num) Num Num)))
(+ (chain (put {} Num true) (put (put {} true true) true true)))
(+ (chain (put {} Num true) (chain (put {} true Num) (put {} Num true))))
(+ (chain (put {} Num Num) (chain (put {} Num Num) (put (put {} Num true) Num true))))
(+ (chain (put {} Num Num) (chain (put {} Num true) (put {} true true))))
(+ (chain (put {} Num true) (chain (put {} true Num) (chain (put {} Num true) (put {} true true)))))
(+ (chain (put {} true Num) (chain (put {} Num Num) (put {} Num true))))
(+ (chain (put (put {} Num Num) Num Num) (put {} Num Num)))
(+ (chain (chain (put {} Num Num) (put {} Num Num))))
(+ (chain (chain (put {} Num Num) (put (put {} Num Num) Num Num))))
(+ (chain (chain (put {} Num true) (put {} true Num))))
(+ (chain (chain (put {} true Num) (put {} Num Num))))
(+ (chain (put (put {} Num true) Num true)))
(+ (chain (put (put {} true true) true true)))
(+ (chain (chain (put {} true true) (put (put {} true true) true true))))
(+ (chain (chain (put {} true true) (chain (put {} true Num) (put {} Num true)))))
(+ (chain (chain (put {} true true) (chain (put {} true Num) (put (put {} Num true) Num true)))))
(- (put (chain (put {} Num true) (put {} true true)) Num Num))
(- (chain (put {} Num true) (put {} Num true)))
(- (chain (put {} Num true) (put {} Num Num)))
(- (chain (put {} true Num) (put {} true true)))
(- (put (put {} Num Num) (put (put {} Num Num))))
(- (put (put {} true Num) (put (put {} Num Num) Num)))
(- (chain (put (put {} Num Num))))
(- (chain (put {} Num Num) (put (put {} Num Num))))
(- (chain (put {} Num Num) (chain (put {} Num Num))))
(- (chain (put {} Num Num) (chain (put (put {} Num Num) Num Num))))
(- (put (put (put (put {} Num Num) Num Num))))
(- (put (put (chain (put {} Num Num) (put {} Num Num)))))
(- (put (put (chain (put {} Num Num) (put (put {} Num Num) Num Num)))))
(- (put (put {} Num Num) (put (chain (put {} Num true) (chain (put {} true Num) (put (put {} Num Num) Num Num))))))
(- (put Num))
(- (put (put {} Num Num) true))
(- (put (put {} Num Num) (put {} true Num)))
(- (put (put {} true Num) Num))
(- (put (put {} true Num) (put {} Num Num)))
(- (put (put {} Num Num) Num (put (put {} Num Num) Num Num)))
(- (chain Num))
(- (chain true))
(- (chain (put {} Num Num) (put {} true Num)))
(- (chain (put {} Num Num) (put (put {} true true) true true)))
(- (chain (put {} Num true) true))
(- (chain (put {} Num true) (put {} Num Num)))
(- (put (put {} true Num) (put (put {} true Num) true Num)))
(- (put (put {} true Num) (chain (put {} true Num) (put {} Num Num))))
(+ (cons Num (cons Num nil)))
(+ (cons nil (cons nil nil)))
(- (cons nil Num))
(+ (cons (cons Num nil) nil))
(+ (cons true (cons true nil)))
(- (cons nil true))
(- (cons Num (cons true nil)))
(- (cons true (cons Num nil)))
