(Num (i));(true (b));(Str (s));(nil (l a));(cons (-> a (-> (l a) (l a))));(none (o a));(some (-> a (o a)));(value (-> (o a) (-> a a)));(get (-> (o a) a));(join (-> (o (o a)) (o a)));(is_none (-> (o a) (b)));(is_some (-> (o a) (b)));(to_list (-> (o a) (l a)))

(+ (cons Num (cons Num nil)))
(+ (cons Num (to_list (some Num))))
(+ (cons true (cons true nil)))
(+ (cons Str (cons Str nil)))
(+ (cons nil (cons nil nil)))
(+ (cons (cons Num nil) nil))
(+ (cons (some Num) (cons none nil)))
(+ (cons (value (some Num) Num) nil))
(+ (cons (value none Num) (cons Num nil)))
(+ (cons (to_list (some Num)) (cons nil nil)))
(+ (cons (to_list none) nil))
(+ (cons (get (some Num)) (cons Num nil)))
(+ (cons (join (some (some Num))) nil))
(+ (cons (join (some none)) (cons none nil)))
(+ (cons (is_some (some Num)) (cons true nil)))
(+ (cons (is_none none) (cons true nil)))
(+ (cons (is_none (some Num)) nil))
(+ (cons (to_list (join (some (some Num)))) nil))
(+ (cons (get none) nil))
(+ (cons Str (cons Str nil)))
(+ (cons (some true) (cons (some true) nil)))
(+ (some (some Str)))
(+ (value (some Num) Num))
(+ (value (some true) true))
(+ (value (some (cons Num nil)) (cons Num nil)))
(+ (value none Str))
(+ (get (some Num)))
(+ (get (some true)))
(+ (get (some (cons Num nil))))
(+ (join (some (some Num))))
(+ (join (some (some true))))
(+ (join (some none)))
(+ (join none))
(+ (is_some (some Num)))
(+ (is_some none))
(+ (is_some (some true)))
(+ (is_none none))
(+ (is_none (some Num)))
(+ (is_none (some (cons Num nil))))
(+ (to_list (some Num)))
(+ (to_list (some true)))
(+ (to_list none))
(+ (to_list (some (cons Num nil))))
(+ (cons (to_list (some Num)) nil))
(+ (cons (value (some Num) Num) nil))
(+ (cons (get (some Num)) nil))
(+ (cons (join (some (some Num))) nil))
(+ (cons (is_some (some Num)) (cons true nil)))
(+ (cons (is_none none) (cons true nil)))

(- (cons Num Num))
(- (cons true Num))
(- (cons Num (cons true nil)))
(- (cons true (cons Num nil)))
(- (cons (some Num) (cons Num nil)))
(- (value (some Num) true))
(- (join (some Num)))
(- (is_some Num))
(- (to_list Num))
(- (cons (some Num) (cons (some true) nil)))
(- (cons (to_list (some Num)) (cons Num nil)))
(- (cons (join (some (some Num))) (cons Num nil)))
(- (value none Num)))
(- (cons (is_none none) (cons Num nil)))
(- (cons (is_none none) (cons true nil)))
(- (cons (some (cons Num nil)) (cons (some Num) nil)))
(- (cons Num (cons true nil)))
(- (cons true (cons Num nil)))
(- (value (some Num) true))
(- (value Num))
(- (get Num))
(- (get (cons Num nil)))
(- (join (some Num)))
(- (is_some Num))
(- (is_some (cons Num nil)))
(- (is_none true))
(- (some Num Num))
(- (to_list Num))
(- (to_list (cons Num nil)))
(- (cons (value (some Num) Num) (cons true nil)))
(- (cons (join (some (some Num))) (cons Num nil)))