(Num (i));(true (b));(Str (s));(pair (-> a (-> b (p a b))));(fst (-> (p a b) a));(snd (-> (p a b) b));(nil (l a));(cons (-> a (-> (l a) (l a))))

(- (cons (snd (pair Num Num)) (cons Str nil)))
(+ (cons (snd (pair Num Str)) (cons Str nil)))

(+ (cons (fst (pair Num Str)) (cons Num nil)))
(+ (cons (fst (pair Num Num)) (cons Num (cons Num nil))))
(+ (cons (snd (pair Str Num)) (cons Num nil)))
(+ (cons (fst (pair true Num)) (cons true nil)))
(+ (cons (snd (pair Str true)) (cons true (cons true nil))))
(+ (cons (fst (pair Num Str)) (cons (fst (pair Num Num)) nil)))
(+ (cons (snd (pair Str true)) (cons (snd (pair Num true)) nil)))
(+ (cons (fst (pair (pair Num Num) Str)) (cons (pair Num Num) nil)))
(+ (cons (snd (pair true (pair Num Str))) (cons (pair Num Str) nil)))
(+ (cons (fst (pair Num (pair Str true))) (cons Num nil)))
(+ (cons (snd (pair Num (pair Str true))) (cons (pair Str true) nil)))
(+ (cons (fst (pair Num Num)) (cons (snd (pair Num Num)) (cons Num nil))))
(+ (cons (snd (pair true true)) (cons (fst (pair true true)) nil)))
(+ (cons (fst (pair (pair Num Str) true)) (cons (pair Num Str) nil)))
(- (cons (fst (pair Num Str)) (cons true nil)))
(- (cons (snd (pair true Num)) (cons Str nil)))
(- (cons (fst (pair (pair Num Num) Str)) (cons Num nil)))
(- (cons (snd (pair true (pair Num Str))) (cons Str nil)))
(- (cons (fst (pair Num Str)) (cons (snd (pair Num Str)) nil)))
(- (cons (fst (pair Num (pair Str true))) (cons (pair Str true) nil)))
(- (cons (snd (pair Num (pair Str true))) (cons Num nil)))
(- (cons (fst (pair Num Str)) (cons Str nil)))
(- (cons (snd (pair Num Str)) (cons Num nil)))
(- (cons (fst (pair (pair Num Str) true)) (cons true nil)))


(+ (cons Num (cons Num nil)))
(+ (cons nil (cons nil nil)))
(- (cons nil Num))
(+ (cons (cons Num nil) nil))
(+ (cons true (cons true nil)))
(- (cons nil true))
(- (cons Num (cons true nil)))
(- (cons true (cons Num nil)))



(+ (pair Num Num))
(+ (pair Str Num))
(+ (pair true Str))
(+ (pair (pair Num Num) Str))
(+ (pair Num (pair Str true)))
(+ (pair (fst (pair Num Str)) Num))
(+ (pair (snd (pair Num Str)) Str))
(+ (pair (fst (pair (pair Num Str) true)) Num))
(+ (pair (snd (pair true (pair Num Str))) (pair Num Str)))
(+ (fst (pair (pair Num Str) true)))
(+ (snd (pair (pair Num Str) true)))
(+ (fst (pair (fst (pair Num Str)) (snd (pair true Str)))))
(+ (snd (pair (pair Num Num) (pair Str true))))
(+ (pair (fst (pair Num Num)) (snd (pair Str Str))))
(+ (pair (snd (pair Num (pair Str true))) Num))
(+ (pair (fst (pair (pair Num Num) Str)) (snd (pair true Num))))
(+ (fst (pair (pair Num Str) (pair true Num))))
(+ (snd (pair (pair Num Str) (pair true Num))))
(+ (pair (fst (snd (pair Num (pair Str true)))) Num))
(+ (pair Num (fst (snd (pair true (pair Num Str))))))
(+ (fst (pair (pair Num (fst (pair Str Num))) Str)))
(+ (snd (pair true (pair (snd (pair Num Str)) Num))))
(- (snd Str))
(- (fst true))
(- (snd Num))
(- (fst (fst (pair Num Str))))
(- (snd (snd (pair Num Str))))
(- (fst Num))
(- (snd true))
