(i (i));(b (b));({} (d a b));(put (-> (d k v) (-> k (-> v (d k v)))));(chain (-> (d a b) (-> (d b c) (d a c))))
(- (put (chain (put {} i b) (put {} b b)) i i))




(+ (chain {} {}))




(+ (chain (put {} b b) (put {} b b)))
(- (chain (put {} i b) (put {} i b)))
(- (chain (put {} i b) (put {} i i)))
(- (chain (put {} b i) (put {} b b)))
(+ (put (chain (put {} i b) (put {} b i)) i i))
(+ (put (put {} i b) i b))
(+ (put (chain (put {} i b) (put {} b b)) i b))
(+ (chain (put {} i b) (chain (put {} b i) (put {} i i))))
(+ (chain (put {} i i) (chain (put {} i b) (put (put {} b i) b i))))
(+ (chain {} (put {} i b)))
(+ (chain (put {} b i) (put (put {} i i) i i)))
(+ (chain (put {} i b) (put (put {} b b) b b)))
(+ (chain (put {} i b) (chain (put {} b i) (put {} i b))))
(+ (chain (put {} i i) (chain (put {} i i) (put (put {} i b) i b))))
(+ (chain (put {} i i) (chain (put {} i b) (put {} b b))))
(+ (chain (put {} i b) (chain (put {} b i) (chain (put {} i b) (put {} b b)))))
(+ (chain (put {} b i) (chain (put {} i i) (put {} i b))))
(+ (chain (put (put {} i i) i i) (put {} i i)))
(+ (chain (chain (put {} i i) (put {} i i))))
(+ (chain (chain (put {} i i) (put (put {} i i) i i))))
(+ (chain (chain (put {} i b) (put {} b i))))
(+ (chain (chain (put {} b i) (put {} i i))))
(+ (chain (put (put {} i b) i b)))
(+ (chain (put (put {} b b) b b)))
(+ (chain (chain (put {} b b) (put (put {} b b) b b))))
(+ (chain (chain (put {} b b) (chain (put {} b i) (put {} i b)))))
(+ (chain (chain (put {} b b) (chain (put {} b i) (put (put {} i b) i b)))))
(- (put (put {} i i) (put (put {} i i))))
(- (put (put {} b i) (put (put {} i i) i)))
(- (chain (put (put {} i i))))
(- (chain (put {} i i) (put (put {} i i))))
(- (chain (put {} i i) (chain (put {} i i))))
(- (chain (put {} i i) (chain (put (put {} i i) i i))))
(- (put (put {} i i)))
(- (put (put (put (put {} i i) i i))))
(- (put (put (chain (put {} i i) (put {} i i)))))
(- (put (put (chain (put {} i i) (put (put {} i i) i i)))))
(- (put (put {} i i) (put (chain (put {} i b) (chain (put {} b i) (put (put {} i i) i i))))))
(- (put i))
(- (put (put {} i i) b))
(- (put (put {} i i) (put {} b i)))
(- (put (put {} b i) i))
(- (put (put {} b i) (put {} i i)))
(- (put (put {} i i) i (put (put {} i i) i i)))
(- (chain i))
(- (chain b))
(- (chain (put {} i i) (put {} b i)))
(- (chain (put {} i i) (put (put {} b b) b b)))
(- (chain (put {} i b) b))
(- (chain (put {} i b) (put {} i i)))
(- (put (put {} b i) (put (put {} b i) b i)))
(- (put (put {} b i) (chain (put {} b i) (put {} i i))))