(Num (i));(true (b));(nil (l a));(cons (-> a (-> (l a) (l a))))

(+ (cons Num (cons Num nil)))
(+ (cons nil (cons nil nil)))
(+ (cons (cons Num nil) nil))
(+ (cons true (cons true nil)))
(- (cons nil Num))
(- (cons nil true))
(- (cons Num (cons true nil)))
(- (cons true (cons Num nil)))
