// 0_basics.types, 1_comparison.types

// pos I wrote
((<) Str Str )
((>) Str Str )
((<=) Char Char)
((>=) Str Str)
(compare Str Str )
(min Str Str )
(max Char Char )
((<) Str Str)
((>) Str Str)
((<=) Char Char )
((>=) Str Str )
(compare Str Str)
(min Str Str)
(max Char Char)
((=) Num Num )
((=) true false)
((<>) Num Num)
((<>) true false )
((<) Num Num )
((<) ((compare Num Num)) Num )
((>) Num Num )
((>) ((compare Num Num)) Num )
((<=) Num Num)
((<=) ((compare Num Num)) Num)
((>=) Num Num)
((>=) ((compare Num Num)) Num)
(compare Num Num )
((=) (compare Num Num) Num )
(min Num Num )
((=) (min Num Num) Num )
(max Num Num )
((=) (max Num Num) Num )
((==) Num Num)
((==) true false )
((!=) Num Num)
((!=) true false )
((=) Num Num )
((=) true false)
((==) ((=) Num Num) true )
((<>) Num Num)
((<>) true false )
((==) ((<>) Num Num) true)
((<) Num Num )
((<) ((compare Num Num)) Num )
((==) ((<) Num Num) true )
((==) ((<) ((compare Num Num)) Num) false)
((>) Num Num )
((>) ((compare Num Num)) Num )
((==) ((>) Num Num) true )
((==) ((>) ((compare Num Num)) Num) false)
((<=) Num Num)
((<=) ((compare Num Num)) Num)
((==) ((<=) Num Num) true)
((==) ((<=) ((compare Num Num)) Num) false )
((>=) Num Num)
((>=) ((compare Num Num)) Num)
((==) ((>=) Num Num) true)
((==) ((>=) ((compare Num Num)) Num) false )
(compare Num Num )
((=) (compare Num Num) Num )
((<) (compare Num Num) Num )
(min Num Num )
((=) (min Num Num) Num )
((<) (min Num Num) Num )
(max Num Num )
((=) (max Num Num) Num )
((<) (max Num Num) Num )
((==) Num Num)
((==) true false )
((==) ((=) Num Num) true )
((!=) Num Num)
((!=) true false )
((==) ((!=) Num Num) true)
((=) Num Num)
((=) Num Num)
((=) true true)
((=) Str Str)
((=) (=) (=))

((<>) Num Num)
((<>) true false)
((<>) Str Str)
((<>) (=) (=))

((<) Num Num)
((<) Num Num)
((<) Str Str)

((>) Num Num)
((>) Num Num)
((>) Str Str)

((<=) Num Num)
((<=) Num Num)
((<=) Str Str)

((>=) Num Num)
((>=) Num Num)
((>=) Str Str)

(compare Num Num)
(compare Str Str)
(compare true (< Num Num))
(compare true (<= Num Num))
(compare true (> Num Num))
(compare true (>= Num Num))
(compare true (= Num Num))
(compare true (<> Num Num))

(compare (< Num Num) (= Num Num))
(compare (<= Num Num) (= Num Num))
(compare (> Num Num) (= Num Num))
(compare (>= Num Num) (= Num Num))
(compare (<> Num Num) (= Num Num))

(min Num Num)
(min Str Str)

(max Num Num)
(max Str Str)

((=) ((<>) Num Num) true)
((=) ((<) Num Num) true)
((=) ((>) Num Num) true)
((=) ((=) Num Num) true)
((=) (compare Num Num) Num)
((=) (min Num Num) Num)

((<>) ((=) Num Num) true)
((<>) ((<) Num Num) false)
((<>) ((>) Num Num) false)
((<>) (compare Num Num) Num)
((<>) (max Num Num) Num)

((<) (min Num Num) Num)
((<) (max Num Num) Num)
((<) (compare Num Num) Num)
((<) (compare Num Num) Num)
((<) (compare Str Str) Num)

((>) (max Num Num) Num)
((>) (min Num Num) (Num))
((>) (compare Num Num) Num)
((>) (compare Str Str) Num)

((<=) (min Num Num) Num)
((<=) (max Num Num) Num)
((<=) (compare Num Num) Num)
((<=) (compare Str Str) Num)

((>=) (max Num Num) Num)
((>=) (min Num Num) Num)
((>=) (compare Num Num) Num)
((>=) (compare Str Str) Num)

(compare (min Num Num) (max Num Num))
(compare ((=) Num Num) true)
(compare ((<>) Num Num) true)
(compare (compare Num Num) Num)
(compare (compare Str Str) Num)

(min (max Num Num) Num)
(min (min Num Num) Num)
(min (compare Num Num) Num)
(min (compare Num Num) Num)
(min (compare Str Str) Num)

(max (min Num Num) Num)
(max (max Num Num) Num)
(max (compare Num Num) Num)
(max (compare Num Num) Num)
(max (compare Str Str) Num)

((<) compare compare)
((<=) compare compare)
((<>) compare compare)
((=) compare compare)
((>=) compare compare)
(compare compare compare)
(max max max)
(min min min)

// neg I wrote
((=) Num Str )
((<>) Num Str)
((<) Num Str )
((>) Num Str )
((<=) Num Str)
((>=) Num Str)
(compare Num Str )
(min Num Str )
(max Num Str )
((==) Num Str)
((!=) Num Str)
((=) Num Str)
((<>) Num Str )
((<) Num Str)
((>) Num Str)
((<=) Num Str )
((>=) Num Str )
(compare Num Str)
(min Num Str)
(max Num Str)
((==) Num Str )
((!=) Num Str )
((=) Num Str)
((<>) Num Str)
((<) true Num)
((>) Str Num)
(min Num ((=) Num Num))
((<=) (compare Num Num) true)
((>=) (min Num Num) Str)
((<>) ((<) Num Num) Num)
((<) (compare Num Num) Str)
((>) ((=) Num Num) Num)
(compare Num Str)
(min true Num)
(max Str Num)
(compare Num (min Str Str))
(min (max Num Num) Str)
(max Str (compare Str Str))



// LLM generated
(= Num Num)
(= Str Str)
(= true true)
(= Char Char)

(<> Num Num)
(<> Str Str)
(<> true false)

(< Num Num)
(< Str Str)

(> Num Num)
(> true false)

(<= Num Num)
(<= Str Str)

(>= Num Num)
(>= true false)

(compare Num Num)
(compare Str Str)
(compare true false)
(compare Char Char)

(min Num Num)
(min Str Str)

(max Num Num)
(max true false)

(== Num Num)
(== Str Str)

(!= Num Num)
(!= true false)

(= (min Num Num) Num)
(= (max Num Num) Num)
(= (compare Num Num) Num)
(< (compare Num Num) Num)
(> (compare Str Str) Num)
(min (compare Num Num) Num)
(max (compare Str Str) Num)

(= Num Str)
(= true Num)
(< Num Str)
(min Num Str)
(compare Num true)

// compare returns int: feed into arithmetic comparisons
(< (compare Num Num) Num)
(> (compare Num Num) Num)
(<= (compare Num Num) Num)
(>= (compare Num Num) Num)
(<> (compare Num Num) Num)
(compare (compare Num Num) Num)
(compare (compare Str Str) Num)
(compare (compare Num Num) (compare Str Str))
(min (compare Num Num) Num)
(max (compare Num Num) Num)
(min (compare Str Str) (compare Num Num))
(max (compare Num Num) (compare Str Str))
(min (compare Char Char) (compare Num Num))

// =, <>, <, >, <=, >= return bool: feed back into bool comparisons
(= (= Num Num) true)
(= (= Num Num) false)
(= (< Num Num) true)
(= (> Num Num) false)
(= (<= Num Num) (<= Num Num))
(= (>= Num Num) (>= Num Num))
(<> (= Num Num) false)
(<> (< Num Num) (<> Num Num))
(compare (= Num Num) true)
(compare (< Num Num) (> Num Num))
(compare (<= Num Num) (>= Num Num))
(compare (<> Num Num) (= Num Num))
(compare (= Str Str) (= Num Num))
(min (= Num Num) true)
(max (< Num Num) false)
(min (= Num Num) (< Num Num))
(max (<> Num Num) (>= Str Str))

// min/max return same type as inputs: feed back into comparisons
(= (min Num Num) Num)
(= (max Num Num) Num)
(= (min Str Str) Str)
(< (min Num Num) Num)
(< (min Num Num) (max Num Num))
(> (max Num Num) Num)
(> (max Num Num) (min Num Num))
(<= (min Num Num) (max Num Num))
(>= (max Num Num) (min Num Num))
(compare (min Num Num) (max Num Num))
(compare (max Str Str) (min Str Str))
(min (max Num Num) Num)
(max (min Num Num) Num)
(min (min Num Num) (max Num Num))
(max (max Num Num) (min Num Num))
(min (max Str Str) Str)
(max (min Str Str) Str)

// invalid: mixing output types across type boundaries
(min (compare Num Num) true)
(= (compare Num Num) Str)
(< (= Num Num) Num)
(min (max Num Num) Str)
(compare Num (min Str Str))
