// 0_basics.types, 4_arith.types

(succ Num)
(pred Num)
((~-) Num)
((~+) Num)

((+) Num Num)
((-) Num Num)
(( * ) Num Num)
((/) Num Num)
(( mod ) Num Num)
(abs Num)

(succ max_int)
(pred min_int)
(succ (pred Num))
(pred (succ Num))
(pred ((~+) Num))
(abs ((~-) Num))
((~-) (abs Num))
((+) (abs Num) Num)
((/) (abs Num) Num)
(( * ) (succ Num) (pred Num))
(( mod ) (abs Num) Num)
((-) ((+) Num Num) Num)
((-) ((/) Num Num) Num)
((-) (( mod ) Num Num) Num)
((/) (( * ) Num Num) Num)

(succ (succ (succ Num)))

((~-) Str)
((-) Num Str)
((-) Str)
((+) Num Str)
((+) Str)
(( * ) true)
(( * ) Num true)
(abs Str)
(( mod ) Num true)
(( mod ) true)
((/) Num Str)
((/) Str)

// succ/pred/abs/~- return int: chain them
(succ (succ (succ (succ Num))))
(pred (pred (pred Num)))
(abs (abs (abs Num)))
((~-) ((~-) Num))
((~+) ((~+) Num))
(succ (abs (pred Num)))
(pred (succ (abs Num)))
(abs ((+) (succ Num) (pred Num)))
(abs (( mod ) (succ Num) (pred Num)))
(abs (( / ) (succ Num) (pred Num)))
((~-) (abs ((-) Num Num)))

// + - * / mod return int: use as arguments to more arithmetic
(succ ((+) Num Num))
(succ ((/) Num Num))
(succ (( mod ) Num Num))
(pred ((-) Num Num))
(abs (( * ) Num Num))
((~-) ((/) Num Num))
((+) (succ Num) (pred Num))
((+) (abs Num) (abs Num))
((/) (succ Num) (pred Num))
((/) (abs Num) (abs Num))
(( mod ) (succ Num) (pred Num))
(( mod ) (abs Num) (abs Num))
((-) (( * ) Num Num) (( * ) Num Num))
(( * ) (succ Num) (succ Num))
(( * ) (succ Num) ((~+) Num))
((/) (abs Num) (succ Num))
(( mod ) (abs ((+) Num Num)) (succ Num))
((+) ((+) Num Num) ((+) Num Num))
(( * ) ((+) Num Num) ((-) Num Num))
((-) (( * ) (succ Num) Num) (pred Num))
(abs (( mod ) ((-) Num Num) (succ Num)))

// show outputs are ints by passing to functions expecting int
(succ max_int)
(succ min_int)
((+) min_int Num)
((/) min_int Num)
(pred min_int)
((+) max_int Num)
(( mod ) max_int Num)
((-) Num min_int)
(abs ((-) max_int min_int))

// invalid chaining
(succ ((+) Num Str))
(abs (( * ) true Num))

// arithmetic does not accept booleans
(succ true)
(succ false)
(pred true)
((~-) false)
((~+) true)
(abs false)
((+) true Num)
((+) Num false)
((-) false true)
(( * ) true false)
((/) Num true)
(( mod ) false Num)

// arithmetic does not accept function values
(succ (+))
(pred (-))
((~-) (*))
(abs (/))
(abs abs)
((+) (+))
((+) Num (-))
((/) (+))
((/) Num (-))
(( * ) (+))
(( mod ) (+))
(( mod ) Num (-))
((~+) (+))

// arithmetic output is not a function: cannot apply it
((succ Num) Num)
((pred Num) Num)
(((+) Num Num) Num)
((abs Num) Num)
(((~+) Num) Num)
(((~-) Num) Num)
(((/) Num Num) Num)
((( mod ) Num Num) Num)
