// 0_basics.types, 6_float.types, 11_pair.types

(~-. Flt)
(~+. Flt)

(+. Flt Flt)
(-. Flt Flt)
( *. Flt Flt)
(/. Flt Flt)
( ** Flt Flt)

(sqrt Flt)
(exp Flt)
(log Flt)
(log10 Flt)
(expm1 Flt)
(log1p Flt)
(cos Flt)
(sin Flt)
(tan Flt)
(acos Flt)
(asin Flt)
(atan Flt)
(atan2 Flt Flt)
(hypot Flt Flt)
(cosh Flt)
(sinh Flt)
(tanh Flt)
(acosh Flt)
(asinh Flt)
(atanh Flt)
(ceil Flt)
(floor Flt)
(abs_float Flt)
(copysign Flt Flt)
(mod_float Flt Flt)

(frexp Flt)
(fst (frexp Flt))
(snd (frexp Flt))

(ldexp Flt Num)

(modf Flt)
(fst (modf Flt))
(snd (modf Flt))

(float Num)
(float_of_int Num)
(truncate Flt)
(int_of_float Flt)

(classify_float Flt)
(classify_float infinity)
(classify_float neg_infinity)
(classify_float nan)
(classify_float max_float)
(classify_float min_float)
(classify_float epsilon_float)

(+. (sqrt Flt) (exp Flt))
( *. (floor Flt) (ceil Flt))
(abs_float (~-. Flt))
(sqrt (abs_float Flt))
(+. (float_of_int Num) Flt)

(+. Flt Num)
(sqrt Num)
(ldexp Flt Flt)
(atan2 Flt Num)
(copysign Flt Num)

// unary float ops return float: chain them
(sqrt (abs_float Flt))
(exp (log Flt))
(log (exp Flt))
(ceil (floor Flt))
(floor (ceil Flt))
(abs_float (~-. Flt))
(~-. (abs_float Flt))
(sqrt (sqrt Flt))
(sin (asin Flt))
(cos (acos Flt))
(atan (tan Flt))
(log (expm1 Flt))
(expm1 (log1p Flt))

// binary float ops return float: chain them
(+. (sqrt Flt) (exp Flt))
(-. (ceil Flt) (floor Flt))
( *. (cos Flt) (cos Flt))
(/. (exp Flt) (exp Flt))
( ** (abs_float Flt) Flt)
(atan2 (sin Flt) (cos Flt))
(hypot (abs_float Flt) (abs_float Flt))
(copysign (abs_float Flt) Flt)
(mod_float (abs_float Flt) (abs_float Flt))

// deeper chains
(sqrt (+. ( *. Flt Flt) ( *. Flt Flt)))
(abs_float (-. (ceil Flt) (floor Flt)))
(exp (abs_float (~-. Flt)))
(log (abs_float (+. Flt Flt)))
(+. (sin Flt) ( *. (cos Flt) (cos Flt)))

// float/int conversions: output used in further ops
(+. (float Num) (float_of_int Num))
(sqrt (float_of_int Num))
(abs_float (float_of_int Num))
(succ (truncate (abs_float Flt)))
(succ (int_of_float (floor Flt)))
(float (succ (truncate Flt)))
(+. Flt (float (truncate Flt)))

// frexp/modf outputs (pairs) extracted and reused
(+. (fst (frexp Flt)) Flt)
(ldexp Flt (snd (frexp Flt)))
(+. (fst (modf Flt)) (snd (modf Flt)))
(abs_float (fst (modf Flt)))
(floor (fst (modf Flt)))

// invalid chaining
(sqrt (truncate Flt))
(+. Flt (truncate Flt))
(succ (sqrt Flt))
(ldexp (float Num) (float Num))
