import Data.List
import Data.Maybe

inc x = x + 1


_ = filter not ((:) True [])
_ = (++) (repeat False) (singleton False)
_ = all even ((:) 0 ((:) 0 []))
_ = null []
_ = iterate id 0
_ = and ((:) True ((:) False []))
_ = any not ((:) False ((:) (not False) []))
_ = catMaybes ((:) (Just 0) (repeat (listToMaybe ((:) (Just 0) []))))
_ = map even ((:) 0 [])
_ = (:) (head ((:) 0 [])) []
_ = concatMap maybeToList (repeat (Just True))
_ = (:) True (replicate 0 True)
_ = (:) (head ((:) 0 ((:) 0 []))) []
_ = inc 0
_ = (:) 0 (singleton 0)
_ = id 0
_ = id (:)
_ = (:) 0 (singleton 0)
_ = id []
_ = tail ((:) True [])
_ = (++) (repeat True) (singleton True)
_ = inc (length ((:) True []))
_ = (:) False (replicate 0 True)
_ = dropWhile null (singleton (Just 0))
_ = filter not ((:) False [])
_ = id True
_ = dropWhile null (singleton [])
_ = inc (fromMaybe 0 (Just 0))
_ = id Nothing
_ = takeWhile even []
_ = listToMaybe ((:) 0 [])
_ = catMaybes ((:) Nothing (repeat (listToMaybe [])))
_ = concatMap maybeToList (repeat Nothing)
_ = id []
_ = maybeToList Nothing
_ = inc (head (filter even ((:) 0 ((:) 0 []))))
_ = inc (length ((:) False ((:) True [])))
_ = and ((:) True [])
_ = isJust Nothing
_ = isNothing ((!?) (replicate 0 0) 0)
_ = length []
_ = iterate inc 0
_ = inc 0
_ = isJust (Just True)
_ = isNothing ((!?) (repeat True) True)
_ = iterate id True
-- _ = mapMaybe ((!?) ((:) 0 [])) (repeat 0)
_ = take 0 ((++) (reverse ((:) True [])) (repeat True))
_ = uncons (repeat True)
_ = iterate inc 0
_ = iterate not False
_ = inc (head (filter even ((:) 0 [])))
_ = length ((:) 0 ((:) 0 []))
_ = null ((:) 0 [])
_ = inc (fromMaybe 0 Nothing)
_ = uncons ((:) 0 ((:) 0 []))
_ = map even ((:) 0 ((:) 0 []))
-- _ = mapMaybe ((!?) ((:) 0 [])) (repeat 0)
_ = maybeToList (Just True)
_ = all even ((:) 0 ((:) 0 []))
_ = any not ((:) True ((:) (not True) []))
_ = iterate not True
_ = not True
_ = or ((:) True [])
_ = not False
_ = null ((:) 0 [])
_ = null ((:) False [])
_ = null (singleton (Just 0))
_ = or ((:) False ((:) True []))
_ = take 0 ((++) (reverse ((:) False ((:) True []))) (repeat False))
_ = takeWhile even ((:) 0 ((:) 0 []))
_ = tail ((:) False [])
_ = False even (listToMaybe ((:) 0 ((:) 0 [])))
_ = uncons ((:) 0 ((:) 0 []))
_ = uncons (repeat False)
_ = (++) ((:) True []) (singleton True)
_ = all isJust ((:) (Just 0) (repeat Nothing))
_ = and (singleton False)
_ = any id ((:) False ((:) True []))
_ = catMaybes ((:) (Just 0) ((:) Nothing []))
_ = concatMap id (repeat (Just 0))
_ = (:) (head ((:) 0 [])) (repeat 0)
_ = (:) (Just 0) (singleton (Just 0))
_ = dropWhile isNothing (singleton (Just 0))
_ = filter id ((:) Nothing [])
_ = id Nothing
_ = id (repeat False)
_ = id (replicate 0 True)
_ = inc (fromMaybe 0 (Just 0))
_ = inc (head (filter (not . isJust) ((:) (Just 0) (repeat Nothing))))
_ = inc (length ((:) False ((:) False [])))
_ = length (repeat True)
_ = map not ((:) True ((:) False []))
_ = mapMaybe (listToMaybe ((:) 0 ((:) 0 (singleton 0)))) (repeat True)
_ = maybeToList (Just False)
_ = null (repeat True)
_ = null (singleton True)
_ = or ((:) False [])
_ = take 0 (repeat True)
_ = takeWhile isJust (singleton (Just 0))
_ = tail (singleton (Just False))
_ = uncons (repeat False)
_ = (++) (repeat True) (singleton False)
_ = all not ((:) True ((:) True []))
_ = and (singleton True)
_ = any isJust ((:) (Just 0) (repeat Nothing))
_ = catMaybes ((:) (Just 0) (repeat (Just 0)))
_ = concatMap maybeToList (repeat (Just False))
_ = (:) (head (filter isNothing ((:) Nothing []))) (repeat 0)
_ = (:) True (singleton (Just 0))
_ = dropWhile null (repeat True)
_ = filter (not . isJust) (repeat (Just True))
_ = id (repeat True)
_ = id (filter even (repeat 0))
_ = id (Just 0)
_ = inc (fromMaybe True (Just True))
_ = inc (head (filter not ((:) True (repeat True))))
_ = inc (length (repeat True))
_ = isJust (Just False)
-- _ = isNothing ((!?) (replicate 0 False) False)
_ = iterate (not True) True
_ = iterate inc (Just 0)
_ = iterate not (Just True)
_ = length ((:) False ((:) False (repeat True)))
_ = map isJust ((:) (Just True) (repeat Nothing))
-- _ = mapMaybe ((!?) ((:) True [])) (repeat True)
_ = maybeToList (Just False)
_ = not (Just True)
_ = null (repeat Nothing)
_ = null (repeat True)
_ = or (repeat (Just True))
_ = take 0 (repeat False)
_ = takeWhile isJust (repeat (Just 0))
_ = tail (repeat False)
_ = uncons (singleton False)



-- wrongfully failed
_ = catMaybes ((:) (Just 0) ((:) Nothing []))
