package oneast

import query.Query

class Scheduler(val query: Query) {
    fun nextQuery(): Pair<SearchState, Query> {
        TODO()
    }
}
/*
enumeration input should be
    seed search state
    could wrap in Query:
        relevant posexs
        relevant negexs
    oracle

enumerateoneast should take a seed searchstate as input, which is generated by the scheduler.
val seed = SearchState(query.names, query.names.map { TypeHole() }, mapOf())
The scheduler/orchestrator also generates subqueries, which are subsets of examples relevant to the provided seed

Overall loop to pick subset of examples and enumerate from some known types. USE ARRS

btw, use a real logging library

"For big libraries, go in rounds. Isolate a subset which could be independently solved for
For example, interesting nontrivial functions on Lists of Maybes in the Maybe library, but it's good if we figure out List, int, bool first. Then we'll have examples where we know the types for some subexpressions
Curriculum design. Most strongly connected subgraphs? Smallest cut"
	"Partitioning examples: Pick random example, take set of all constructs in that example. Take all examples that involve only those constructs. if examples not big enough add examples that add fewest num new constructs. Or, for each new name, which has the fewest edges to other names not in my set? (did that sentence make sense)
Can use universe of examples to guide in finding inital set of names with enough support of self contained examples. If we start with 100 examples, want a subset of names for which i can find 20 examples."
	"Consider how to backtrack if, after coming up with types for subset of examples, we realize something is wrong. Is the only way we can be wrong by over restricting?
Failure mode: Say we pick examples of fns with lists and ints. Might overfit and miss that lists are polymorphic - we will be overly strict
Then in a CEGISy way, we could try to find some other examples that could force us to turn concrete labels into variables, or bound vars into fresh vars. We can go in and see did I actually make an example for this parameter with more than one type? Was it a coincidence? This counterexample step could be with LLM or not. Prompt: Make something reasonable for the following (candidate) type
Identify blind spots not tested by examples - generate more in goal directed manner from type system. Shouldn't need to restart from scratch. Only generalizations or refinements"
 */
