package oneast

import query.Example
import test.SomeHaskell
import kotlin.math.min

/*
enumeration input should be
    seed search state
    could wrap in Query:
        relevant posexs
        relevant negexs
    oracle

enumerateoneast should take a seed searchstate as input, which is generated by the scheduler.
val seed = SearchState(query.names, query.names.map { TypeHole() }, mapOf())
The scheduler/orchestrator also generates subqueries, which are subsets of examples relevant to the provided seed

Overall loop to pick subset of examples and enumerate from some known types. USE ARRS

btw, use a real logging library

Partitioning examples: Pick random example, take set of all constructs in that example.
Take all examples that involve only those constructs. if examples not big enough add examples
that add fewest num new constructs. Or, for each new name, which has the fewest edges to
other names not in my set? (did that sentence make sense)
Can use universe of examples to guide in finding initial set of names with enough support of
self contained examples.
If we start with 100 examples, want a subset of names for which i can find 20 examples.


Consider how to backtrack if, after coming up with types for subset of examples, we realize something is wrong. Is the only way we can be wrong by over restricting?
Failure mode: Say we pick examples of fns with lists and ints. Might overfit and miss that lists are polymorphic - we will be overly strict
Then in a CEGISy way, we could try to find some other examples that could force us to turn concrete labels into variables, or bound vars into fresh vars. We can go in and see did I actually make an example for this parameter with more than one type? Was it a coincidence? This counterexample step could be with LLM or not. Prompt: Make something reasonable for the following (candidate) type
Identify blind spots not tested by examples - generate more in goal directed manner from type system. Shouldn't need to restart from scratch. Only generalizations or refinements"
 */

fun main() {
    val h = SomeHaskell

    val start = System.currentTimeMillis()
    println("Total names: ${h.names.size}")

    val initial = Scheduler().selectNames(h.unsignedExamples, h.names.toList(), k = 10)
    println("Initial selection: $initial")

    // TODO if there are less than k remaining just return all of them
    val extended =
        Scheduler().extendSelection(h.unsignedExamples, h.names.toList(), initial, k = 10)
    println("Extended selection: ${initial + extended}")
    println("${System.currentTimeMillis() - start} ms") // 2000-2300 ms
    // TODO print covered examples
    // TODO after getting a selection, save the state of the scorer for later so we can recompute a
    // little less maybe
    //      honestly only saves us milliseconds so not a big deal
    //      if we don't have enough examples for each function, try iteratively increasing k? or
    // just give user an error message. bc if even for the best examples we don't have enough, we
    // need more.
}

// TODO: Take query as input, maintain state? or just let it get garbage collected lol
/** The below code was written by ChatGPT */
class Scheduler {
    private fun greedy(
        base: Set<String>, // already chosen elements
        candidates: List<String>, // universe to select from
        scorer: Scorer,
        k: Int, // number of elements to add
    ): Set<String> {
        require(base.all { it !in candidates })
        // Initialize coverage from base
        for (name in base) {
            scorer.addName(name)
        }

        val added = mutableSetOf<String>()

        while (added.size < k) {
            var bestName: String? = null
            var bestGain = 0.0

            for (name in candidates) {
                if (added.contains(name)) continue
                val gain = scorer.marginalGain(name)
                if (gain > bestGain) {
                    bestGain = gain
                    bestName = name
                }
            }

            if (bestName == null)
                break // the bestGain is zero only when none of the names appear in any example.

            scorer.addName(bestName)
            added.add(bestName)
        }

        return added
    }

    // --- Public wrapper: select from empty ---
    fun selectNames(
        examples: List<Example>,
        allNames: List<String>,
        k: Int,
    ): Set<String> {
        val scorer = Scorer(examples)
        return greedy(emptySet(), allNames, scorer, k)
    }

    // --- Public wrapper: extend existing selection ---
    fun extendSelection(
        examples: List<Example>,
        allNames: List<String>,
        fixed: Set<String>,
        k: Int,
    ): Set<String> {
        val scorer = Scorer(examples)
        val available = allNames.filterNot { fixed.contains(it) }
        return greedy(fixed, available, scorer, k)
    }
}

// Scorer with coverage counts
class Scorer(private val examples: List<Example>) {
    private val m = examples.size

    // For each example, number of elements already chosen
    val coverage = IntArray(m)

    // Precompute which examples contain each name
    val nameToExamples: Map<String, List<Int>> = run {
        val map = mutableMapOf<String, MutableList<Int>>()
        for ((i, ex) in examples.withIndex()) {
            for (name in ex.names) {
                map.computeIfAbsent(name) { mutableListOf() }.add(i)
            }
        }
        map
    }

    // relaxed score using coverage counts
    fun score(): Double {
        var total = 0.0
        for (i in 0 until m) {
            total += min(coverage[i].toDouble() / examples[i].names.size, 1.0)
        }
        return total
    }

    // marginal gain of adding a candidate name
    fun marginalGain(name: String): Double {
        var gain = 0.0
        val indices = nameToExamples[name] ?: return 0.0
        for (i in indices) {
            if (coverage[i] < examples[i].names.size) {
                val before = coverage[i].toDouble() / examples[i].names.size
                val after = (coverage[i] + 1).toDouble() / examples[i].names.size
                gain += min(after, 1.0) - min(before, 1.0)
            }
        }
        return gain
    }

    // add a name and update coverage counts
    fun addName(name: String) {
        val indices = nameToExamples[name] ?: return
        for (i in indices) {
            coverage[i]++
        }
    }

    // true objective: number of fully covered examples
    fun countFullyCovered(): Int {
        var count = 0
        for (i in 0 until m) {
            if (coverage[i] >= examples[i].names.size) count++
        }
        return count
    }
}
