name:                 benchmarks
version:              0.1.0.0
visibility:           public
id:                   benchmarks-0.1.0.0-inplace
key:                  benchmarks-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           vyd2@cornell.edu
author:               Vivian Ding
abi:                  inplace
exposed:              True
exposed-modules:      Lib
import-dirs:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/build

library-dirs:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/build

library-dirs-static:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/build

dynamic-library-dirs:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/build

data-dir:             /home/vivianyyd/type-synth/src/main/haskell/.
hs-libraries:         HSbenchmarks-0.1.0.0-inplace
depends:
    base-4.18.3.0
    pandoc-3.8.3-1a334d2014f38f5ce8a1f8ead2ca9c2c9ac1da2be95059bba5b22fa98aea9016
    text-2.0.2

haddock-interfaces:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/doc/html/benchmarks/benchmarks.haddock

haddock-html:
    /home/vivianyyd/type-synth/src/main/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/benchmarks-0.1.0.0/doc/html/benchmarks
